export default defineAppConfig({
    ui: {
        colors: {
            primary: "iris",
            secondary: "azure",
            neutral: "zinc",
        },
        icons: {
            arrowDown: "i-mingcute:arrow-down-fill",
            arrowLeft: "i-mingcute:arrow-left-fill",
            arrowRight: "i-mingcute:arrow-right-fill",
            arrowUp: "i-mingcute:arrow-up-fill",
            caution: "i-mingcute:warning-fill",
            check: "i-mingcute:check-small-fill",
            chevronDoubleLeft: "i-mingcute:arrows-left-fill",
            chevronDoubleRight: "i-mingcute:arrows-right-fill",
            chevronDown: "i-mingcute:down-small-fill",
            chevronLeft: "i-mingcute:left-small-fill",
            chevronRight: "i-mingcute:right-small-fill",
            chevronUp: "i-mingcute:up-small-fill",
            close: "i-mingcute:close-small-fill",
            copy: "i-mingcute:copy-2-fill",
            copyCheck: "i-mingcute:check-fill",
            dark: "i-mingcute:moon-fill",
            drag: "i-mingcute:dot-grid-fill",
            ellipsis: "i-mingcute:more-1-fill",
            error: "i-mingcute:close-circle-fill",
            external: "i-mingcute:arrow-right-up-fill",
            eye: "i-mingcute:eye-2-fill",
            eyeOff: "i-mingcute:eye-close-fill",
            file: "i-mingcute:file-fill",
            folder: "i-mingcute:folder-fill",
            folderOpen: "i-mingcute:folder-open-fill",
            hash: "i-mingcute:hashtag-fill",
            info: "i-mingcute:information-fill",
            light: "i-mingcute:sun-fill",
            loading: "i-mingcute:loading-3-fill",
            menu: "i-mingcute:menu-fill",
            minus: "i-mingcute:minus-circle-fill",
            panelClose: "i-mingcute:layout-leftbar-close-fill",
            panelOpen: "i-mingcute:layout-leftbar-open-fill",
            plus: "i-mingcute:add-circle-fill",
            reload: "i-mingcute:refresh-2-fill",
            search: "i-mingcute:search-2-fill",
            stop: "i-mingcute:stop-circle-fill",
            success: "i-mingcute:check-circle-fill",
            system: "i-mingcute:monitor-fill",
            tip: "i-mingcute:bulb-fill",
            upload: "i-mingcute:upload-2-fill",
            warning: "i-mingcute:warning-fill",
        },
        toaster: {
            slots: {
                viewport: "bottom-12!",
            },
        },
        badge: {
            variants: {
                size: {
                    xs: {
                        base: "text-xs px-1 py-0.25 gap-1 rounded-sm",
                    },
                    sm: {
                        base: "text-xs px-1.5 py-0.5 gap-1 rounded-sm",
                    },
                },
            },
        },
    },
});
